name: AliyunContainerService Image Sync
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  # push:
  schedule:
    # 每周一早晨 8 同步
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      file:
        description: "指定要使用的镜像同步文件的路径"
        type: string
        required: true
        default: "images_list/kubernetes/images-v1.23.3.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install image-syncer
        env:
          image_syncer_version: v1.3.1
        run: |
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/${image_syncer_version}/image-syncer-${image_syncer_version}-linux-amd64.tar.gz
          tar -zxf image-syncer-${image_syncer_version}-linux-amd64.tar.gz
      - name: config
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALI_USERNAME: ${{ secrets.ALI_USERNAME }}
          ALI_PASSWORD: ${{ secrets.ALI_PASSWORD }}
        run: |
          cat > auth.json <<EOF
          {
              "registry.cn-hangzhou.aliyuncs.com": {
                  "username": "${ALI_USERNAME}",
                  "password": "${ALI_PASSWORD}"
              },
              "docker.io": {
                  "username": "${DOCKER_USERNAME}",
                  "password": "${DOCKER_PASSWORD}"
              }
          }
          EOF
      - name: images sync
        shell: bash
        env:
          FILE_PATH: ${{ github.event.inputs.file }}
        run: |
          if [ -z ${FILE_PATH} ]; then
            ./image-syncer --proc=5 --auth=auth.json --images=images.yaml --retries=3 --arch=amd64 --registry='registry.cn-hangzhou.aliyuncs.com' --namespace='dd_k8s'
          else
            ./image-syncer --proc=5 --auth=auth.json --images=${{ github.event.inputs.file }} --retries=3 --arch=amd64 --registry='registry.cn-hangzhou.aliyuncs.com' --namespace='dd_k8s'
          fi
      - name: check log
        run: |
          ls -al
