name: Container Images Sync
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  push:
  schedule:
  # 
  - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: install image-syncer
      env:
        image_syncer_version: v1.3.0
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${image_syncer_version}/image-syncer-${image_syncer_version}-linux-amd64.tar.gz
        tar -zxf image-syncer-${image_syncer_version}-linux-amd64.tar.gz
    - name: config
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        sed -i "s@DOCKER_USERNAME@${DOCKER_USERNAME}@g" auth.json
        sed -i "s@DOCKER_PASSWORD@${DOCKER_PASSWORD}@g" auth.json
        cat config.yaml
    - name: images sync
      run: |
        ./image-syncer --proc=20 --auth=auth.json --images=images.json --retries=3
