name: Container Images Sync
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  push:
  schedule:
  # 
  - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: install image-syncer
      env:
        image_syncer_version: v1.3.0
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${image_syncer_version}/image-syncer-${image_syncer_version}-linux-amd64.tar.gz
        tar -zxf image-syncer-${image_syncer_version}-linux-amd64.tar.gz
    - name: config
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALI_USERNAME: ${{ secrets.ALI_USERNAME }}
        ALI_PASSWORD: ${{ secrets.ALI_PASSWORD }}
      run: |
        cat > auth.json <<EOF
        {        
            "quay.io": {
                "username": "xxx",             
                "password": "xxxxxxxxx",
                "insecure": true
            },
            "registry.cn-hangzhou.aliyuncs.com": {
                "username": "${ALI_USERNAME}",
                "password": "${ALI_PASSWORD}"
            },
            "docker.io": {
                "username": "${DOCKER_USERNAME}",
                "password": "${DOCKER_PASSWORD}"
            },
            "quay.io/coreos": {
                "username": "abc",              
                "password": "xxxxxxxxx",
                "insecure": true  
            }
        }
        EOF
    - name: images sync
      run: |
        ./image-syncer --proc=20 --auth=auth.json --images=images.json --retries=3
